### ISSUE TITLE
Open editor from the source code

### ISSUE THREAD

**Issue by benoit-dubreuil** [piotr-j/bte2#2]
I cloned the repository and then imported the project into IntelliJ with gradle. I looked at all subprojects but non are executable. Also, there's no documentation.

How can one use this editor without having to code? Do I absolutely need to create  program to open the editor?

**Comment by piotr-j** [comment]
You can run bte-test, its based on one of the gdx-ai tests. Its a standard libgdx game setup.
If you want to use it for your game, you have to code. Its not meant to be standalone, but run with the game. You can use bte-window to open it in new os window, instead of same windows as the game. But that requires lwjgl3 so its in separate project.
